TJJ-004: Create Sales Employee API
Java-Jesters/soniak-bew-project pull request #15
Opened 2024-10-16 14:26 UTC by dylanBkainos

2024-10-16 14:38 UTC, MatthewJKainos requested changes

2024-10-16 14:38 UTC, MatthewJKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                            "WHERE Employee.employeeId IN"
Perhaps try adding spaces to the end of these lines?
And also maybe testing your code..?

2024-10-16 14:38 UTC, MatthewJKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                        resultSet.getString("firstName" + " " + "lastName"),
Close but not quite :)

2024-10-16 14:39 UTC, lukemKainos requested changes

2024-10-16 14:39 UTC, lukemKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                        resultSet.getString("firstName" + " " + "lastName"),
out of interest would "firstName lastName" not work?

2024-10-16 14:39 UTC, lukemKainos commented on src/main/java/org/example/daos/SalesEmployeeDao.java
> +                            "FROM SalesEmployee)"
this query isnt formnatted correctly

2024-10-16 14:39 UTC, lukemKainos commented on src/main/java/org/example/mappers/SalesEmployeeMapper.java
> +    public static List<SalesEmployeeResponse> mapSalesEmployeeListToSalesEmployeeResponseList(
maybe change this to 'toSalesEmployeeResponseList

2024-10-16 14:39 UTC, lukemKainos commented on src/main/java/org/example/models/SalesEmployee.java
> +        this.commissionRate = commissionRate;
uhh where is this set?

2024-10-16 14:39 UTC, lukemKainos commented on src/main/java/org/example/models/SalesEmployeeResponse.java
> +    private String nationalInsuranceNumber;
do we need the setters for these? if its a response why would we not set as final and just return the object

2024-10-16 15:13 UTC, lukemKainos approved these changes

2024-10-17 08:25 UTC, MatthewJKainos approved these changes

2024-10-17 08:27 UTC, CForde-Kainos approved these changes

2024-10-17 08:27 UTC, merged