TJJ-019: Create Employee Table
Java-Jesters/soniak-bew-project pull request #2
Opened 2024-10-15 14:40 UTC by CForde-Kainos

2024-10-15 14:42 UTC, MatthewJKainos requested changes
This is an empty file

2024-10-15 14:49 UTC, MatthewJKainos requested changes

2024-10-15 14:49 UTC, MatthewJKainos commented on src/main/resources/migration/V1__create_employee_table.sql
> +    lastName varchar(50),
There is a miss-match between tabbing and spacing.
Could we use tabbing for consistency?

2024-10-15 15:21 UTC, MatthewJKainos approved these changes

2024-10-15 15:31 UTC, lukemKainos requested changes

2024-10-15 15:31 UTC, lukemKainos commented on src/main/resources/migration/V1__create_employee_table.sql
> +);
line indent incorrect

2024-10-16 08:26 UTC, lukemKainos approved these changes

2024-10-16 08:28 UTC, merged