TJJ-001: Created Delivery Employee Table
Java-Jesters/soniak-bew-project pull request #3
Opened 2024-10-15 15:06 UTC by dylanmckk

2024-10-15 15:38 UTC, MatthewJKainos requested changes
Indentation has been done using spaces.
Could we update these to use tabbing?

2024-10-16 08:24 UTC, MatthewJKainos approved these changes

2024-10-16 08:39 UTC, lukemKainos requested changes

2024-10-16 08:39 UTC, lukemKainos commented on src/main/resources/db/migration/V2__create_deliv_emp_tbl.sql
> +CREATE TABLE DeliveryEmployee (
dont like this file name

2024-10-16 08:39 UTC, lukemKainos commented on src/main/resources/db/migration/V2__create_deliv_emp_tbl.sql
> +	id int NOT NULL,
what is id?

2024-10-16 08:43 UTC, dylanmckk commented on src/main/resources/db/migration/V2__create_deliv_emp_tbl.sql
> +CREATE TABLE DeliveryEmployee (
https://mtlynch.io/human-code-reviews-1/

2024-10-16 09:11 UTC, lukemKainos approved these changes

2024-10-16 09:11 UTC, merged