TJJ-005: Created Project Table
Java-Jesters/soniak-bew-project pull request #4
Opened 2024-10-15 15:21 UTC by dylanmckk

2024-10-15 15:30 UTC, MatthewJKainos reviewed
Happy with the PR,
I'm just going to hold off from approving because we have to wait for prs #3 and #4 to be merged before merging this one.

2024-10-16 08:25 UTC, MatthewJKainos approved these changes

2024-10-16 08:27 UTC, lukemKainos requested changes

2024-10-16 08:27 UTC, lukemKainos commented on src/main/resources/db/migration/V4__create_project_tbl.sql
> +	`value` decimal(11, 2) NOT NULL,
What is value?

2024-10-16 08:31 UTC, MatthewJKainos commented on src/main/resources/db/migration/V4__create_project_tbl.sql
> +	`value` decimal(11, 2) NOT NULL,
The specification states "Able to store a name, value and client"
Would we be better off storing this as `projectValue`?

2024-10-16 08:40 UTC, lukemKainos commented on src/main/resources/db/migration/V4__create_project_tbl.sql
> +	`value` decimal(11, 2) NOT NULL,
yes project value please, value just doesn't make sense in this labeling pattern

2024-10-16 09:47 UTC, lukemKainos approved these changes

2024-10-16 10:03 UTC, lukemKainos approved these changes

2024-10-16 10:05 UTC, MatthewJKainos requested changes

2024-10-16 10:05 UTC, MatthewJKainos commented on src/main/resources/db/migration/V5__create_project_table.sql
> +	FOREIGN KEY (clientId) REFERENCES Client(clientId),
This restraint will fail because the Client table doesn't exist yet

2024-10-16 10:05 UTC, MatthewJKainos commented on src/main/resources/db/migration/V5__create_project_table.sql
> +	FOREIGN KEY (techLeadId) REFERENCES DeliveryEmployee(deliveryEmployeeId),
The id in `DeliveryEmployee` is just `employeeId`

2024-10-16 10:05 UTC, MatthewJKainos commented on src/main/resources/db/migration/V5__create_project_table.sql
> +	FOREIGN KEY (salesEmployeeId) REFERENCES SalesEmployee(salesEmployeeId)
Same here, should just be `employeeId`

2024-10-16 10:18 UTC, MatthewJKainos reviewed
All good, but we just need to wait for migration 5 to be merged

2024-10-16 10:29 UTC, MatthewJKainos approved these changes
Ok we merge now :)

2024-10-16 10:29 UTC, merged